baseURL = 'https://hugo.ivelum.com/'
languageCode = 'en-us'
title = "ivelum"
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[markup.goldmark.extensions.typographer]
disable = true

[output]
home = ['html']
section = ['html']

[[deployment.targets]]
name = "s3"
URL = "s3://hugo.ivelum.com?region=eu-north-1"
