baseURL = 'https://hugo.ivelum.com/'
languageCode = 'en-us'
title = "ivelum"
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[output]
  home = ['html']
  section = ['html']

[deployment]
  [[deployment.targets]]
  name = "s3"
  URL = "s3://hugo.ivelum.com?region=eu-north-1"
