baseURL = 'https://ivelum.com/'
languageCode = 'en-us'
title = "ivelum"
disableKinds = ['taxonomy', 'term']

[markup.goldmark.extensions.typographer]
disable = true

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
style = 'friendly'

[output]
home = ['html']
section = ['html']

[[deployment.targets]]
name = "s3"
URL = "s3://static.new.ivelum.com?region=eu-north-1"
cloudFrontDistributionID = "E1BS3XJ8OWJCVR"
