baseURL = 'https://ivelum.com/'
locale = 'en-US'
title = "ivelum"
disableKinds = ['taxonomy', 'term']

[markup.goldmark.extensions.typographer]
disable = true

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
style = 'friendly'

[output]
home = ['html']
section = ['html']

[deployment]
maxDeletes = -1

[[deployment.matchers]]
pattern = '^.+\.(css|js|mjs|svg|woff2?|ttf|png|jpe?g|gif|webp|avif|ico|pdf|mp4|webm|webmanifest)$'
cacheControl = 'public, max-age=2592000'
force = true

[[deployment.targets]]
name = "s3"
URL = "s3://static.new.ivelum.com?region=eu-north-1"
cloudFrontDistributionID = "E1BS3XJ8OWJCVR"
